### ISSUE TITLE
Band reference interface

### ISSUE THREAD

**Issue by uchchwhash** [daleroberts/nrt-predict#21]
It would be great if this library also supported references to bands by names rather than their indices.

While a 3d array `arr[y, x, band]` interface works great for certain algorithms, a `dict` of 2d arrays interface `{band_name: arr[y, x]}` would make the code more readable and maintainable at the cost of little or no performance penalties for most algorithms.

Of course, this would also mean that standard ODC `dask.array`-backed `xarray.Dataset` interface would just work, without this library needing to depend on either of those libraries.

Under this scheme, for example,
```python
def predict(self, pre, pst):
    pre_nbr = (pre[:, :, 6] - pre[:, :, 8]) / (pre[:, :, 6] + pre[:, :, 8])
    pst_nbr = (pst[:, :, 6] - pst[:, :, 8]) / (pst[:, :, 6] + pst[:, :, 8])
    return pre_nbr - pst_nbr
```
would look like
```python
def predict(self, pre, pst):
    pre_nbr = (pre['nbar_B06'] - pre['nbar_B08']) / (pre['nbar_B06'] + pre['nbar_B08'])
    pst_nbr = (pst['nbar_B06'] - pst['nbar_B08']) / (pst['nbar_B06'] + pst['nbar_B08'])
    return pre_nbr - pst_nbr
```
note that these band names should work with ODC. Or maybe even better
```python
def predict(self, pre, pst):
    pre_nbr = (pre['nbar_red_edge_2'] - pre['nbar_nir_1']) / (pre['nbar_red_edge_2'] + pre['nbar_nir_1'])
    pst_nbr = (pst['nbar_red_edge_2'] - pst['nbar_nir_1']) / (pst['nbar_red_edge_2'] + pst['nbar_nir_1'])
    return pre_nbr - pst_nbr
```
or something like that, if I recall the band names correctly. This of course needs a dictionary to translate `'nbar_B08'` to `'nbar_nir_1'` somewhere in this code base.

**Comment by uchchwhash** [comment]
Looking at https://github.com/daleroberts/nrt-predict/blob/7684183440c5fe6c1cc4251677b3f0e9b79f63c2/nrtpredict.py#L79 and https://github.com/daleroberts/nrt-predict/blob/7684183440c5fe6c1cc4251677b3f0e9b79f63c2/nrtpredict.py#L151, I would argue that loading data into a dict `data` would actually improve readability of the loading routines too!

**Comment by daleroberts** [comment]
I have substantially rewritten the interface and feature generation now. It should now be able to handle that the case where the data is given as a dict of bands, e.g., `{'B02': array, 'B03': array}` but also (my preferred) dense array style. Not that you guys are interested, but I've also totally reworked `nrtpredict` so that it only loads the bands required by the model which makes it much faster.

**Comment by RichardScottOZ** [comment]
I think people using it will appreciate fast!
